- examples/tgw_inbound_combined_with_gwlb/app1_spoke.tf
Many users are mainly interested to see whether http and https
application can respond on the app1 spoke vpc. It is a more friendly
test than ssh.
> in app1_lb add ports 80 and 443

- modules/vmseries/README.md
- modules/vmseries/outputs.tf
The output is usable for a Load Balancer Target Group working in `"ip"`
mode instead of the usual `"instance"` mode (the `target_type` input).
The `"ip"` mode is specifically required for panos overlay routing
scenarios. Generally, it is required for loadbalancing any non-primary
interface of a VM on EC2.
> feat(vmseries): add output `network_interfaces`

- examples/tgw_inbound_combined_with_gwlb/files/plugins/.keep
- modules/bootstrap/main.tf
- modules/bootstrap/variables.tf
- modules/gwlb/README.md
A new input source_root_directory allows to have separate bootstrap.xml
files for separate availability zones. With a Panorama, it allows to
have separate dgname and tplname per availability zone.
This appears the only way to configure panos to have different route
next hops for different availability zones.
commit-id:fa21d4c8
> feat(bootstrap): add input `source_root_directory`

- go.mod
- go.sum
Change is required in order to use terratest against state files created by Terraform versions starting with 1.0.0. Without it test execution fails with a message similar to:
```--- FAIL: TestMain (56.03s)
plan.go:66: 
Error Trace:    plan.go:66
generictt.go:60
main_test.go:39
Error:          Received unexpected error:
unsupported state format version: expected "0.1", got "0.2"
Test:           TestMain
FAIL
FAIL    github.com/PaloAltoNetworks/terraform-aws-vmseries-modules/tests/bootstrap      56.029s
FAIL
```
Run all the available tests.
> fix(tests) bump github.com/hashicorp/terraform-json to v0.12.0

- examples/vpc_endpoint/README.md
- examples/vpc_endpoint/example.tfvars
- examples/vpc_endpoint/main.tf
- examples/vpc_endpoint/variables.tf
- examples/vpc_endpoint/versions.tf
- modules/vpc_endpoint/main.tf
- modules/vpc_endpoint/outputs.tf
- modules/vpc_endpoint/variables.tf
- modules/vpc_endpoint/versions.tf
The module handles general VPC endpoints of both types, the Gateway
ones (like S3) and the Interface ones (like the REST APIs).
The module is not intended for GWLB Endpoints, for these there is a
separate module `gwlb_endpoint_set`.
Input descriptions co-authored by michalbil.
Co-authored-by: michalbil <92343355+michalbil@users.noreply.github.com>
commit-id:37edddeb
> feat(vpc_endpoint): add a new module `vpc_endpoint`

- examples/tgw_inbound_combined_with_gwlb/README.md
- examples/tgw_inbound_combined_with_gwlb/outputs.tf
- modules/vmseries/README.md
- modules/vmseries/outputs.tf
Add an output with public IPs created within a module.
The address may be further used as inputs for other resources.
Deploy example using terraform 1.1.4.
> feat(vmseries): Add output with created public IPs

- .gitignore
- .pre-commit-config.yaml
Ignore .terraform.lock.hcl in git and when running terraform-docs.
If the file is taken into account when generating docs it can cause a sort of a "race condition" between local and CI hook executions.
Checked local vs. CI results.
> chore: Ignore .terraform.lock.hcl

- modules/bootstrap/README.md
- modules/bootstrap/init-cfg.txt.tmpl
- modules/bootstrap/main.tf
- modules/bootstrap/variables.tf
Add plugin-op-commands variable in template file.
Without plugin-op-commands in template file - it is not possible to associate gwlbe with sub-interface or enable overlay routing.
Tested by pushing new variable to green deployment and inspect the ```show system bootstrap status``` command.
- Bug fix (non-breaking change which fixes an issue) - Issue #176 
- [x ] I have updated the documentation accordingly.
> fix(bootstrap): Add bootstrap plugin variable

- modules/vmseries/main.tf
Closing #188
> When vmseries_ami_id is specified in the vmseries module the plan errors out.
Fix the issue in using `coalesce()` with an empty tuple in our code base.
Running the examples from the repository which reference the `vmseries` module without an issue:
- `vmseries_combined_with_gwlb_natgw`
- `standalone_vmseries_with_userdata_bootstrap`
> fix(vmseries): fix the issue where users cannot specify `vmseries_ami_id` 

- examples/standalone_vmseries_with_userdata_bootstrap/README.md
- examples/tgw_inbound_combined_with_gwlb/README.md
- modules/bootstrap/README.md
- modules/bootstrap/main.tf
- modules/bootstrap/outputs.tf
- modules/bootstrap/variables.tf
- modules/gwlb/README.md
- modules/gwlb_endpoint_set/README.md
- modules/nat_gateway_set/README.md
- modules/panorama/README.md
- modules/subnet_set/README.md
- modules/transit_gateway/README.md
- modules/transit_gateway_attachment/README.md
- modules/transit_gateway_peering/README.md
- modules/vmseries/README.md
- modules/vpc/README.md
- modules/vpc_route/README.md
New bootstrap feature allows to support existing bucket without creating new from bootstrap module. Closes #177 
Pushing content update from terraform code is not common operation from CI/CD.
The content for vmseries update is manage by Security Teams.
The changes are comply with existing TGW example - the options can be set 
> feat(bootstrap): add support for existing bucket

- modules/vmseries/README.md
- modules/vmseries/main.tf
- modules/vmseries/variables.tf
Enable EBS encryption by default for the `vmseries` module. Closes #191 
Enhance security posture in our code base.
I've tested the changes by running the `standalone_vmseries_with_userdata_bootstrap` example with the `ebs_encrypted` parameter set to `true` and `false` respectively in two different AWS regions and compared the output to check whatever the default KMS key for the selected region is selected or not for the EBS encryption.
> feat(vmseries): enable EBS encryption by default

- modules/transit_gateway/README.md
- modules/transit_gateway/main.tf
- modules/transit_gateway/outputs.tf
- modules/transit_gateway/variables.tf
Add ability to retrieve an existing Transit Gateway using it's ID. 
Required in situations where to `Name` tag is present or TGW is a shared one - in this case only referencing by ID is possible.
All 3 scenarios were tested:
* create a TGW
* retrieve existing by name
* retrieve existing by ID
> feat(module/transit-gateway): support for retrieving existing TGWs by ID only

- modules/alb/main.tf
In `locals`, add target VM name to the internal map of TG attachments.
Currently there is a bug in the `locals` logic when creating a map of unique target attachments for a particular listener rule. The bug happens when there should be more than one attachments. 
A [future](https://github.com/PaloAltoNetworks/terraform-aws-vmseries-modules/pull/194) example was used to test the code.  
> fix(module/alb): provide unique names for tg listener attachments

- examples/standalone_vmseries_with_userdata_bootstrap/example.tfvars
- examples/standalone_vmseries_with_userdata_bootstrap/main.tf
The current example is not dynamic enough to be used during demos.
The `standalone_vmseries_with_userdata_bootstrap` example has one interface hardcoded in the main.tf file. Whilst this is ok to get yourself familiarised with the modules, this makes it harder to consume the example via Terraform registry and deploy a firewall with multiple interfaces during demos, etc.
The proposed change adds flexibility to add additional interfaces via variables. 
Terraform apply
> Enhance standalone_vmseries_with_userdata_bootstrap example

- examples/vmseries_combined_with_gwlb_natgw/README.md
- examples/vmseries_combined_with_gwlb_natgw/example.tfvars
- examples/vmseries_combined_with_gwlb_natgw/main.tf
- examples/vmseries_combined_with_gwlb_natgw/variables.tf
A simple change. The new feature allows push endpoint config during bootstrap VMSeries phase.
Enabling VPC endpoint configuration requires login into VMSeries machine and run fallowing command:
```request plugins vm_series aws gwlb associate interface ethernet1/1.10 vpc-endpoint ${outbound1}```
The configuration is not available after run ```show plugins vm_series aws gwlb``` until the interface configuration
will be retrieved from Panorama, bootstrap.xml or in manual way.
> feat(example): add endpoint bootstrap via user_data

- modules/asg/main.tf
- modules/panorama/main.tf
- modules/vmseries/main.tf
Add image name regex to match proper image from ambiguous results returned based on AWS ami filters.
Resolves #239 
Deploy one of examples using vmseries image version specified as `10.1.6`, update value to `10.1.6-h6`,  re-apply.
> fix: Fixed panorama/vmseries image selection

- modules/gwlb/README.md
- modules/gwlb/main.tf
We want to use these modules for our PaloAlto GWLB setup, however when we were trying to add a spoke account to this setup, we noticed that the vpc_endpoint_service that gets created in the gwlb module is using inline allowed_principals.
As documented by Terraform, you can't use the inline allowed_principals together with the dedicated aws_vpc_endpoint_service_allowed_principal resource. It makes sense to use the dedicated resource to allow for external (other TF) to be able to add principals to the endpoint_service without having to run the hub (GWLB) TF again.
When creating a new AWS account (in our AWSOrganisation), we want to make it a spoke and plug it in on our security GWLB setup, at that moment we want to allow that account to be able to use the vpc_endpoint_service that is …
> added dedicated resource for allowed_principals on the vpc_endpoint_service

- .pre-commit-config.yaml
Updated checkov version in pre-commit hooks to 2.2.125 that uses a pinned version of packaging module.
It fixes issue #255
It was tested by running ``git commit`` and checking ``checkov`` output.
> chore: checkov pre-commit hook crashes importing packaging

- examples/tgw_inbound_combined_with_gwlb/example.tfvars
- examples/tgw_inbound_combined_with_gwlb/files/config/init-cfg.sample.txt
- examples/tgw_inbound_combined_with_gwlb/vmseries.tf
Associate a VPC Endpoints with VM-Series Interfaces in bootstrap options.
While preparing project for customer with GWLB, there was a need to automatically associate VPC endpoints with VM-Series subinterfaces. In this example similar option is introduced. Moreover that PR is connected with #251, in which feature with GWLB endpoints added to bootstrap options is required.
Code was tested by deploying example [tgw_inbound_combined_with_gwlb](https://github.com/PaloAltoNetworks/terraform-aws-vmseries-modules/tree/main/examples/tgw_inbound_combined_with_gwlb).
Not appropriate
> feat(examples/tgw_inbound_combined_with_gwlb): associate VPC endpoints with VM-Series subinterfaces

- tests/internal/testskeleton/testskeleton.go
Small improvements in checking, if after deployment and running Terraform plan there are planned changes. If yes, then our infrastructure code is not idempotent and test is going to detect such case.
It's a part of #86 
It was tested using Terratest.
> test: Use ResourceChangesMap to check planned changes, do not use regexp

- examples/standalone_panorama/main.tf
- modules/alb/README.md
- modules/alb/main.tf
- modules/vpc_route/outputs.tf
PR #257 with tests and improvements was too big, so in #257 only tests are being merged and in this PR improvements and fixes. PR delivers:
- improvements in modules:
- ``alb`` (resource ``aws_security_group_rule`` added)
- ``vpc_route`` (outputs from module extended)
- fixes in examples:
-  ``standalone_panorama`` (way of retrieving KMS key ID is changed - from alias we need to pass [target_key_arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/kms_alias#target_key_arn), not ARN of the key alias. Problem was reported by @migara and observed during testing, in which after deployment we are checking if there is changes planned, when we run ``terraform plan`` just after deployment)
There was a question to deliver in #257 only changes for tests 
It was tested …
> feat: Improvements needed for tests of modules and fix in panorama example

- modules/subnet_set/main.tf
Added a VPC selector to the subnet_set module to avoid problems with identical names of subnets belonging to different VPCs.
If there are multiple subnets in the region that match the selected name, we will get the multiple EC2 subnets matched error: `use additional restrictions to reduce the matches to a single EC2 subnet. `
The check was based on a region where there were about a dozen subnets with the same name. After adding the `vpc_id` parameter, the expected subnet ID was obtained.
- Bug fix
> fix(module/subnet_set): Added VPC selector to match existing subnets in VPC

- examples/combined_vmseries_and_autoscale/README.md
- examples/combined_vmseries_and_autoscale/example-natgw-lambda-vpc.tfvars
- examples/combined_vmseries_and_autoscale/example-no-natgw-lambda-no-vpc.tfvars
- examples/combined_vmseries_and_autoscale/main.tf
Example [combined_vmseries_and_autoscale](https://github.com/PaloAltoNetworks/terraform-aws-vmseries-modules/tree/main/examples/combined_vmseries_and_autoscale) initially was delivered in topology with NAT Gateway used by Lambda working in VPC and by VM-Series, for which untrust interfaces don't have public IP. There is also possibility to deploy example without NAT Gateway, where Lambda is outside VPC and VM-Series instances have untrust interfaces with public IP. This PR delivers 2 different tfvars files for both cases.
PR extends #295 and provides answer for question about deploying example without NAT Gateway.
Code was deployed in the lab, integrated with Panorama and tested with inbound, outbound and eastwest traffic.
> feat(example/combined_vmseries_and_autoscale): Additional tfvars for deployment without NAT Gateway

- modules/bootstrap/README.md
- modules/bootstrap/main.tf
PR delivers fixes in module `bootstrap` connected with error:
```
Error: error creating S3 bucket ACL for terratest-module-vmseries-8c71f573ee7558e0: AccessControlListNotSupported: The bucket does not allow ACLs
```
Changes in module were required after [Amazon deployed S3 Security Changes in April of 2023 - S3 now automatically enables S3 Block Public Access and disables S3 access control lists (ACLs) for all new S3 buckets in all AWS Regions](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/). 
Code was tested while working on tests for VM-Series in #286 
> fix(module/bootstrap): Enable ACLs for bucket by setting the object ownership

- .github/workflows/lint_pr_title.yml
- README.md
Add workflow for lint PR in order to check title (needed to correctly prepare semantic release).
Fix GitHub release workflow status (name of the file with workflow was changed in #328 .
Similar solution we have for [Azure VM-Series modules](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/main/.github/workflows/lint_pr_title.yml), so AWS VM-Series modules needs to be adjusted too.
The same workflow is used for [Azure VM-Series modules](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/main/.github/workflows/lint_pr_title.yml).
> feat(workflow): Add workflow for lint PR, fix GitHub release workflow status

- examples/centralized_design/README.md
- examples/centralized_design/main.tf
- examples/centralized_design_autoscale/README.md
- examples/centralized_design_autoscale/main.tf
- examples/combined_design/README.md
- examples/combined_design/main.tf
- examples/combined_design_autoscale/README.md
- examples/combined_design_autoscale/main.tf
- examples/isolated_design/README.md
- examples/isolated_design/main.tf
- examples/isolated_design_autoscale/README.md
- examples/isolated_design_autoscale/main.tf
- examples/panorama_standalone/README.md
- examples/panorama_standalone/main.tf
- examples/vmseries_standalone/README.md
- examples/vmseries_standalone/main.tf
- modules/crosszone_failover/main.tf
PR resolves IAM issues CKV_AWS_290 and CKV_AWS_355 for examples and in modules.
Almost all actions were reused, but specific resources was added (instead of `*`).
Besides that some of them were removed:
- in all examples for VM-Series role it was removed `logs:CreateLogGroup` as plugin `vmseries` is sending metrics, not logs.
- for module `crosszone_failover` it was removed `logs:*`, because in module there was no reference in the code for CloudWatch logs.
Soft fails from #244 
Code was tested by executing `make test` locally.
> fix: Resolve IAM issues CKV_AWS_290 and CKV_AWS_355

- modules/vpc/main.tf
The change updates the tags allocated to the network ACL resource. Currently, all network ACLs created by the VPC module do not contain any shared tags apart from the ACL's name.
The arbitrary tags from `global_tags` variable should be attached to every resource created by the submodule (as stated [in the documentation](https://registry.terraform.io/modules/PaloAltoNetworks/vmseries-modules/aws/latest/submodules/vpc#input_global_tags)), which is currently not the case and introduces inconsistencies in tag allocation. This also makes the network ACLs hard to identify, organize, and filter, as they do not have the expected tags that other resources do.
We've tested the change by modifying the module locally and then re-applying the Terraform plan. All tags from `global_tags` variable were …
> fix(module/vpc): Add global tags to network ACL resource

- .github/workflows/chatops.yml
PR delivers fix for ChatOps - execute ChatOps logic (token, dispatch etc.) only if comment is from pull request and skip comments from issues
Currently ChatOps action is failing for every comment in issues.
Code was tested on internal clone of the repository.
> fix: Skip ChatOps steps for comments in issues

- examples/centralized_design/main.tf
- examples/centralized_design_autoscale/main.tf
- examples/combined_design/main.tf
- examples/combined_design_autoscale/main.tf
- examples/isolated_design/main.tf
- examples/isolated_design_autoscale/main.tf
PR updates all examples with spoke VMs with bitnami-nginx image to 1.25.
In all examples there was used bitnami-nginx image in version 1.21, which is no more available. 
Code was checked locally and on GitHub Actions.
> fix: Update bitnami-nginx image to 1.25 (1.21 is no more available)

- .github/workflows/apply-command.yml
- .github/workflows/chatops.yml
- .github/workflows/help-command.yml
- .github/workflows/idempotence-command.yml
- .github/workflows/plan-command.yml
- .github/workflows/sca-command.yml
- .github/workflows/validate-command.yml
PR is adding full repository name as input for all ChatOps commands workflows.
While running ChatOps for PR created from forked repository, there is an issue with checkout branch, which exists in fork, not in original repository. Please check error messages in https://github.com/PaloAltoNetworks/terraform-aws-vmseries-modules/actions/runs/6322173926.
Code was tested by cloning `terraform-aws-vmseries-modules` into personal account, creating fork from that clone and then executing ChatOps commands for PR created from fork.
> fix: Add repository as input for all ChatOps commands workflows

- modules/subnet_set/README.md
- modules/subnet_set/variables.tf
The change sets the default value for the nacl_associations variable from `null` to `{}` (an empty map).
Currently, the default null value causes Terraform's plan to fail in case no value for the variable is provided - the module (`aws_network_acl_association` resource) expects `nacl_associations` to be iterable (a map of strings), but when the user does not intend to associate any network ACLs with any subnet and skips the variable altogether, it throws an `Invalid for_each argument` error.
The user has to explicitly set a `nacl_associations` variable to an empty map to avoid errors.
By changing the default value from null to an empty map, the resource creation is skipped without any required workarounds from users.
The subnet_sets module was deployed without setting any explicit value …
> fix(module/subnet_sets): Change default value for nacl_associations variable

- examples/isolated_design_autoscale/README.md
PR removes HTML tags `p` from README
Changes were connected with automatic generation of documentation in pan.dev
> fix: One more HTML tag removed from README

- modules/gwlb/README.md
- modules/gwlb/main.tf
- modules/gwlb/variables.tf
PR delivers possibility to define whether or not VPC endpoint connection requests to the service must be accepted by the service owner.
#389
Code was tested by validating it in GitHub Actions.
> feat(module/gwlb): Expose acceptance_required in a variable for gwlb module 

- examples/centralized_design/example.tfvars
- examples/centralized_design_autoscale/example.tfvars
- examples/combined_design/example.tfvars
- examples/combined_design_autoscale/example.tfvars
- examples/isolated_design/example.tfvars
- examples/isolated_design_autoscale/example.tfvars
- examples/panorama_standalone/example.tfvars
- examples/vmseries_standalone/example.tfvars
During release there was an error in `eu-central-1` region. Even when we specify TGW attachment with enabled appliance mode support, attachment is created with disabled value. Then while checking idempotence Terratest propose to change it into `enable` as it's defined in default value for `appliance_mode_support`:
```
TestIdempotence 2023-10-12T04:43:08Z command.go:185:   # module.transit_gateway_attachment["app1"].aws_ec2_transit_gateway_vpc_attachment.this will be updated in-place
TestIdempotence 2023-10-12T04:43:08Z command.go:185:   ~ resource "aws_ec2_transit_gateway_vpc_attachment" "this" {
TestIdempotence 2023-10-12T04:43:08Z command.go:185:       ~ appliance_mode_support                          = "disable" -> "enable"
TestIdempotence 2023-10-12T04:43:08Z command.go:185: …
```
> fix(examples): Change region for examples from eu-central-1 to eu-west-1

- modules/crosszone_failover/README.md
- modules/vpc_endpoint/README.md
- modules/vpn/README.md
Adjust crosszone_failover, vpc_endpoint, vpn modules README headers to display nicely on pan.dev
There has been extra # chars in the beginning and end of reference sections.
Extra char before reference section:
Extra char in the EOF:
> docs: adjust modules readme headers for pan.dev

- modules/asg/main.tf
PR delivers fix for one corner case while executing Terraform code in CI/CD pipelines.
If Terraform code is executed in CI/CD pipeline, then:
- after first `terraform apply` whole infrastructure is being deployed and while installing Lambda, locally on agent executing pipeline there are downloaded Python packages and `installed-pan-os-python` is set from `known after apply` to `false`
- next time when CI/CD pipeline is executed on different agent, `terraform apply` will not install Python packages, because there is no change for `installed-pan-os-python`, it's still `false` as local Python packages are not existing on new agent
- Lambda is being deploying without required Python packages
PR changes that behaviour - instead of using `false`, when there are no Python packages, we are using …
> fix(module/asg): Execute pip to install Python packages (corner case in CI/CD pipeline)

- modules/asg/scripts/lambda.py
PR delivers change in acquiring EC2 instance info - in function `inspect_ec2_instance()` method [`get()`](https://docs.python.org/3.8/library/stdtypes.html) was used to return the value for keys. In comparison to previous approach, if key isn't in the dictionary, then `get()` returns default. If default is not given, it defaults to `None`, so that this method never raises a [KeyError](https://docs.python.org/3.8/library/exceptions.html#KeyError).
Finally - using new approach while manually terminating EC2 instance in AWS console, Lambda doesn't release elastic IP or deregister IP of the instance from target group, but at least it's executed only once. Previously Lambda was failing with `KeyError: 'SubnetId'` and it was executed multiple times after EC2 instance was terminated manually. …
> fix(module/asg): In Lambda KeyError: 'SubnetId' should not be raised after manual EC2 instance termination

- modules/transit_gateway/README.md
- modules/transit_gateway/main.tf
- modules/transit_gateway/variables.tf
The PR introduces new `transit_gateway_cidr_blocks` variables.
The Transit Gateway connect requires to set the variable to build GRE tunnel.
It was run against current examples.
> feat(module/transit_gateway): add TGW cidr blocks
